### ISSUE TITLE
Possible EventEmitter memory leak detected. 11 batchResponse listeners added to [TCPClient]

### ISSUE THREAD

**Issue by yoursunny** [isaacgr/jaysonic#58]
```
$ node --version
v12.15.0
$ node --experimental-modules x.mjs
(node:17248) ExperimentalWarning: The ESM module loader is experimental.
(node:17248) MaxListenersExceededWarning: Possible EventEmitter memory leak dete
cted. 11 batchResponse listeners added to [TCPClient]. Use emitter.setMaxListene
rs() to increase limit
```

```js
import Jaysonic from "jaysonic";

(async () => {

const server = new Jaysonic.server.tcp();
await server.listen();
server.method("f", () => 0);

const client = new Jaysonic.client.tcp();
await client.connect();
for (let i = 0; i <= 11; ++i) {
  await client.batch([
    client.request().message("f"),
  ]);
}

await client.end();
await server.close();

})();
```

This line adds a listener on **batchResponse** event, but nowhere in the code removes this listener.
https://github.com/isaacgr/jaysonic/blob/631ae0a6d4722f39903c2a2879bd61fd8da528d4/src/client/tcp.js#L164

**Comment by isaacgr** [comment]
This doesnt appear to happen for the web client itself. I think the browser garbage collection will handle this, so I'll just fix for the node stuff.
https://stackoverflow.com/questions/2631265/addeventlistener-memory-leaks

Additonally, adding the same code as the node clients to remove listeners appears to remove the listener entirely, so subsequent requests have no 'batchResponse' listener. Which seems weird.

**Comment by isaacgr** [comment]
The below snippet can still cause the issue. Since a listener is created every time a request is sent out. Its cleaned up on response though, so that might be fine?

```js
(() => {
  const server = new Jaysonic.server.tcp();
  server.method("f", () => "0");
  const client = new Jaysonic.client.tcp();

  server.listen().then(() => {
    client.connect().then(() => {
      for (let i = 0; i <= 11; ++i) {
        const request = client.batch([client.request().message("f")]);
        request.then((res) => {
          console.log(res.body);
        });
      }
    });
  });
})();
``

**Comment by isaacgr** [comment]
And for some reason using async/await with the http client doesnt work. But using promises does...
