### ISSUE TITLE
setTimeout is not canceled

### ISSUE THREAD

**Issue by yoursunny** [isaacgr/jaysonic#59]
Environment: Node 12.15.0 on Windows

Snippet to reproduce:
```js
import Jaysonic from "jaysonic";

(async () => {

const server = new Jaysonic.server.tcp();
await server.listen();
server.method("f", () => 0);

const client = new Jaysonic.client.tcp({ timeout: 10 });
await client.connect();
for (let i = 0; i <= 11; ++i) {
  await client.request().send("f");
}

await client.end();
await server.close();

console.log("Program should exit now.");
})();
```

Expect behavior: program exits as soon as the message is printed.
Actual behavior: program does not exit until 10 seconds later.

Root cause: this line sets a timer with `setTimeout`, but the timer is not canceled when the relevant RPC call has been responded.
https://github.com/isaacgr/jaysonic/blob/631ae0a6d4722f39903c2a2879bd61fd8da528d4/src/client/tcp.js#L72
https://github.com/isaacgr/jaysonic/blob/631ae0a6d4722f39903c2a2879bd61fd8da528d4/src/client/tcp.js#L143

**Comment by isaacgr** [comment]
Fixed with #61
